#ifndef ATOMIC_ABUNDANCE_ISOTOPIC_H
#define ATOMIC_ABUNDANCE_ISOTOPIC_H

#define MC_ATOMIC_ABUNDANCE_ELEMENT_MAX          92
#define MC_ATOMIC_ABUNDANCE_ELEMENT_ISOTOPE_MAX  11

extern const double
mc_atom_abundance_isotopic[MC_ATOMIC_ABUNDANCE_ELEMENT_MAX + 1]
                          [MC_ATOMIC_ABUNDANCE_ELEMENT_ISOTOPE_MAX][2];

#endif // ATOMIC_ABUNDANCE_ISOTOPIC_H
