#ifndef ATOMIC_WEIGHT_ISOTOPIC_H
#define ATOMIC_WEIGHT_ISOTOPIC_H

#define MC_ATOMIC_WEIGHT_ELEMENT_MAX          116
#define MC_ATOMIC_WEIGHT_ELEMENT_ISOTOPE_MAX  40

extern const double
mc_atommass_isotopic[MC_ATOMIC_WEIGHT_ELEMENT_MAX + 1]
                    [MC_ATOMIC_WEIGHT_ELEMENT_ISOTOPE_MAX][2];

#endif // ATOMIC_WEIGHT_ISOTOPIC_H
